[package]
name = "abq"
version = "0.1.0"
edition = "2021"

[dependencies]
libabq = { path = "../lib" }
abq_worker_protocol = { path = "../workers/protocol" }

anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }
tempfile = "3.3.0"
signal-hook = "0.3.14"
log = "0.4.17"
env_logger = "0.9.0"
indicatif = "0.16.2"
