[package]
name = "abq"
version = "0.1.0"
edition = "2021"

[dependencies]
abq_queue = { path = "../abq_queue" }
abq_runner_protocol = { path = "../abq_runners/protocol" }
abq_output = { path = "../abq_output" }
abq_workers = { path = "../abq_workers" }
abq_utils = { path = "../abq_utils" }
abq_hosted = { path = "../abq_hosted" }
abq_junit_xml = { path = "../reporters/junit_xml" }

anyhow.workspace = true
signal-hook.workspace = true
serde_json.workspace = true
thiserror.workspace = true

clap.workspace = true
num_cpus.workspace = true
termcolor.workspace = true
atty.workspace = true

tokio.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true

indoc.workspace = true

[dev-dependencies]
insta.workspace = true
paste.workspace = true
serial_test.workspace = true
nix.workspace = true
tempfile.workspace = true

[features]
test-abq-jest = []
