[package]
name = "abq"
version = "0.1.0"
edition = "2021"

[dependencies]
abq_queue = { path = "../abq_queue" }
abq_runner_protocol = { path = "../abq_runners/protocol" }
abq_output = { path = "../abq_output" }
abq_workers = { path = "../abq_workers" }
abq_utils = { path = "../abq_utils" }

anyhow = "1.0.57"
clap = { version = "3.2.4", features = ["derive"] }
tempfile = "3.3.0"
signal-hook = "0.3.14"
log = "0.4.17"
env_logger = "0.9.0"
indicatif = "0.16.2"
serde_json = "1.0.81"
