[package]
name = "abq"
version = "0.1.0"
edition = "2021"

[dependencies]
abq_queue = { path = "../abq_queue" }
abq_runner_protocol = { path = "../abq_runners/protocol" }
abq_output = { path = "../abq_output" }
abq_workers = { path = "../abq_workers" }
abq_utils = { path = "../abq_utils" }
abq_junit_xml = { path = "../reporters/junit_xml" }

anyhow = "1.0.62"
clap = { version = "3.2.17", features = ["derive"] }
tempfile = "3.3.0"
signal-hook = "0.3.14"
indicatif = "0.17.0"
serde_json = "1.0.83"
thiserror = "1.0.32"
num_cpus = "1.13.1"

tokio = { version = "1.20.1", features = ["net", "rt", "rt-multi-thread", "sync", "macros"] }

tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
tracing-appender = "0.2.2"

[dev-dependencies]
insta = "1.18.2"

[features]
test-abq-jest = []
