[package]
name = "abq"
version = "0.1.0"
edition = "2021"

[dependencies]
abq_queue = { path = "../abq_queue" }
abq_runner_protocol = { path = "../abq_runners/protocol" }
abq_output = { path = "../abq_output" }
abq_workers = { path = "../abq_workers" }
abq_utils = { path = "../abq_utils" }
abq_junit_xml = { path = "../reporters/junit_xml" }

anyhow = "1.0.57"
clap = { version = "3.2.15", features = ["derive"] }
tempfile = "3.3.0"
signal-hook = "0.3.14"
indicatif = "0.16.2"
serde_json = "1.0.81"
thiserror = "1.0.31"

tracing = "0.1.35"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
