[package]
name = "abq"
version = "0.1.0"
edition = "2021"

[dependencies]
abq_queue = { path = "../abq_queue" }
abq_runner_protocol = { path = "../abq_runners/protocol" }
abq_output = { path = "../abq_output" }
abq_workers = { path = "../abq_workers" }
abq_utils = { path = "../abq_utils" }
abq_hosted = { path = "../abq_hosted" }
abq_junit_xml = { path = "../reporters/junit_xml" }

anyhow = "1.0.66"
clap = { version = "4.0.24", features = ["derive", "env"] }
tempfile = "3.3.0"
signal-hook = "0.3.14"
indicatif = "0.17.2"
serde_json = "1.0.87"
thiserror = "1.0.37"
num_cpus = "1.14.0"
termcolor = "1.1.3"

tokio = { version = "1.21.2", features = ["net", "rt", "rt-multi-thread", "sync", "macros"] }

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-appender = "0.2.2"
atty = "0.2.14"
indoc = "1.0.7"

[dev-dependencies]
insta = "1.21.1"
paste = "1.0.9"
serial_test = "0.9.0"
nix = "0.25.0"

[features]
test-abq-jest = []
