[workspace]

members = [
  "crates/abq_cli",
  "crates/abq_queue",
  "crates/abq_workers",
  "crates/abq_utils",
  "crates/abq_runners/protocol",
  "crates/abq_runners/echo",
  "crates/abq_runners/exec",
  "crates/abq_runners/generic_test_runner",
  "crates/abq_runners/cargo",
  "crates/reporters/junit_xml",
]
