app = "abq-staging"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
ABQ_FILE_LOG_DIR = "."
ABQ_LOG = "abq=debug"

[experimental]
cmd = [
  "/app/deploy_staging",
]

[[services]]
internal_port = 8080
protocol = "tcp"
tcp_checks = []

  [[services.ports]]
     port = "8080"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[services]]
internal_port = 8081
protocol = "tcp"
tcp_checks = []

  [[services.ports]]
     port = "8081"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[services]]
internal_port = 8082
protocol = "tcp"
tcp_checks = []

  [[services.ports]]
     port = "8082"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[services.script_checks]]
command = "/app/health_staging"
grace_period  = "5s"
interval      = "15s"
restart_limit = 0
timeout       = "1s"

