app = "abq"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
ABQ_FILE_LOG_DIR = "."
ABQ_LOG = "debug,trace"

[experimental]
cmd = [
  "./abq", "start",
  "--bind", "0.0.0.0",
  "--public-ip", "168.220.85.45",
  "--port", "8080",
  "--work-port", "8081",
  "--negotiator-port", "8082",
]

[[services]]
internal_port = 8080
protocol = "tcp"
tcp_checks = []

  [[services.ports]]
     port = "8080"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[services]]
internal_port = 8081
protocol = "tcp"
tcp_checks = []

  [[services.ports]]
     port = "8081"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[services]]
internal_port = 8082
protocol = "tcp"
tcp_checks = []

  [[services.ports]]
     port = "8082"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[[services.script_checks]]
command = "/app/health"
grace_period  = "5s"
interval      = "15s"
restart_limit = 0
timeout       = "1s"
