[package]
edition = "2021"
name = "abq_queue"
version = "0.1.0"

[dependencies]
abq_workers = { path = "../abq_workers" }
abq_runner_protocol = { path = "../abq_runners/protocol" }
abq_echo_worker = { path = "../abq_runners/echo" }
abq_exec_worker = { path = "../abq_runners/exec" }
abq_utils = { path = "../abq_utils" }

anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true

static_assertions.workspace = true

thiserror.workspace = true
tracing.workspace = true

tokio.workspace = true
futures.workspace = true

[dev-dependencies]
abq_utils = { path = "../abq_utils", features = ["expose-native-protocols"] }
abq_with_protocol_version = { path = "../abq_test_support/with_protocol_version" }

ntest.workspace = true
# Needed for testing abq_workers.
# TODO: figure out a better way to implement abq_workers::test_support to avoid this!
procspawn = { version = "0.10.1", features = ["test-support"] }
tempfile.workspace = true
tracing-test.workspace = true
tracing-subscriber.workspace = true
