[package]
edition = "2021"
name = "abq_queue"
version = "0.1.0"

[dependencies]
abq_workers = { path = "../abq_workers" }
abq_runner_protocol = { path = "../abq_runners/protocol" }
abq_echo_worker = { path = "../abq_runners/echo" }
abq_exec_worker = { path = "../abq_runners/exec" }
abq_utils = { path = "../abq_utils" }

anyhow = "1.0.62"
serde = "1.0.143"
serde_derive = "1.0.143"
serde_json = "1.0.83"

thiserror = "1.0.32"
tracing = "0.1.36"

tokio = { version = "1.20.1", features = ["net", "rt", "sync", "macros"] }

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[dev-dependencies]
ntest = "0.8.1"
# Needed for testing abq_workers.
# TODO: figure out a better way to implement abq_workers::test_support to avoid this!
procspawn = { version = "0.10.1", features = ["test-support"] }
tempfile = "3.3.0"
tracing-test = "0.2.3"
