test-suites:
  test-abq:
    command: bash -c 'unset RWX_ACCESS_TOKEN && cargo nextest r --profile ci --all-features --cargo-profile=release-unstable --target="$RUST_TARGET" $@'
    fail-on-upload-error: true
    results:
      path: target/nextest/ci/junit.xml
    output:
      print-summary: true
      reporters:
        github-step-summary:
  # shorthand for running clippy in dev
  dev-clippy:
    command: cargo clippy --workspace --tests --profile=release-unstable --all-features -- --deny warnings
  # shorthand for running tests in dev
  dev-test-abq:
    command: cargo nextest r --all-features --cargo-profile=release-unstable
