[package]
edition = "2021"
name = "abq_junit_xml"
version = "0.1.0"

[dependencies]
abq_utils = { path = "../../abq_utils" }
junit-report = "0.8.2"
strip-ansi-escapes = "0.1.1"

[dev-dependencies]
abq_utils = { path = "../../abq_utils", features = ["expose-native-protocols"] }
insta = "1.21.2"
