[package]
name = "abq_test_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
regex.workspace = true
tokio.workspace = true
tracing-test.workspace = true
termcolor.workspace = true
abq_utils = { path = "../../abq_utils" }
