[env]
# Gives us the path of the workspace root for use in cargo tests without having
# to compute it per-package.
# https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993
ABQ_WORKSPACE_DIR = { value = "", relative = true }

# Without limiting the number of active threads or sequencing tests, we can
# easily hit the number of open FDs (especially on MacOS) during our tests.
# Revisit this when we've made everything async on the worker side.
RUST_TEST_THREADS = "1"

[workspace]
resolver = "2"
