[package]
name = "abq_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = { version = "0.20.6", optional = true }
rustls-pemfile = { version = "1.0.1", optional = true }
tokio-rustls = { version = "0.23.4", optional = true }
serde = "1.0.144"
serde_derive = "1.0.144"
serde_json = "1.0.85"

tokio = { version = "1.21.0", features = ["io-util", "net", "rt", "macros"] }
tracing = "0.1.36"
rand = "0.8.5"
rand_chacha = "0.3.1"

thiserror = "1.0.34"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[features]
default = []
test-actions = []
tls = ["dep:rustls", "dep:rustls-pemfile", "dep:tokio-rustls"]
