[package]
name = "abq_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.142"
serde_derive = "1.0.142"
serde_json = "1.0.83"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[features]
default = []
test-actions = []
