[package]
name = "abq_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = "0.20.6"
rustls-pemfile = "1.0.1"
tokio-rustls = "0.23.4"
serde = "1.0.145"
serde_derive = "1.0.145"
serde_json = "1.0.85"

tokio = { version = "1.21.1", features = ["io-util", "net", "rt", "macros"] }
tracing = "0.1.36"
rand = "0.8.5"
rand_chacha = "0.3.1"

thiserror = "1.0.36"
async-trait = "0.1.57"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[features]
default = []
test-actions = []
