#!/bin/bash

set -exv

cd "$(git rev-parse --show-toplevel)"

if [ -z "$NO_ABQ_JEST" ]; then
  pushd testdata/jest/npm-jest-project
  npm install --include=dev
  popd

  pushd testdata/jest/npm-jest-project-with-failures
  npm install --include=dev
  popd
fi
