[package]
edition = "2021"
name = "abq_workers"
version = "0.1.0"

[dependencies]
abq_runner_protocol = { path = "../abq_runners/protocol" }
abq_generic_test_runner = { path = "../abq_runners/generic_test_runner" }
abq_echo_worker = { path = "../abq_runners/echo" }
abq_exec_worker = { path = "../abq_runners/exec" }
abq_utils = { path = "../abq_utils" }

thiserror = "1.0.36"
procspawn = "0.10.1"
serde = "1.0.145"
serde_derive = "1.0.145"
serde_json = "1.0.85"

parking_lot = "0.12.1"
tokio = { version = "1.21.1", features = ["net", "rt", "rt-multi-thread", "sync", "macros", "time"] }
tracing = "0.1.36"

[dev-dependencies]
procspawn = { version = "0.10.1", features = ["test-support"] }
tempfile = "3.3.0"
tracing-test = "0.2.3"

[features]
default = []
test-actions = ["abq_utils/test-actions"]
