[package]
name = "abq_generic_test_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
abq_runner_protocol = { path = "../protocol" }
abq_utils = { path = "../../abq_utils" }
serde = "1.0.137"
serde_derive = "1.0.137"
serde_json = "1.0.81"

tracing = "0.1.35"

[features]
test-abq-jest = []
