[package]
name = "abq_generic_test_runner"
version = "0.1.0"
edition = "2021"

[lib]
name = "abq_generic_test_runner"
path = "src/lib.rs"

[[bin]]
name = "abq_worker_harness"
path = "src/test_harness.rs"

[dependencies]
abq_runner_protocol = { path = "../protocol" }
abq_utils = { path = "../../abq_utils" }
serde = "1.0.145"
serde_derive = "1.0.145"
serde_json = "1.0.85"

tracing = "0.1.36"
clap = { version = "3.2.22", features = ["derive"] }
anyhow = "1.0.65"
thiserror = "1.0.36"

[features]
test-abq-jest = []

[dev-dependencies]
insta = { version = "1.20.0", features = ["json"] }
