[package]
name = "abq_cargo"
description = "ABQ native runner for the cargo test runner."
version = "0.1.0"
edition = "2021"

[[bin]]
name = "abq_cargo"
path = "src/bin.rs"

[dependencies]
abq_utils = { path = "../../abq_utils" }
serde = "1.0.139"
serde_derive = "1.0.137"
serde_json = "1.0.81"

tracing = "0.1.35"
clap = { version = "3.2.12", features = ["derive"] }
anyhow = "1.0.58"

[features]
test-abq-jest = []

[dev-dependencies]
insta = "1.17.0"
