name: CI

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_and_package_development:
    name: Test and package development build
    uses: ./.github/workflows/test_and_package_development.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  bigtest:
    needs: test_and_package_development
    uses: ./.github/workflows/bigtest.yml
    secrets: inherit
    with:
      version: ${{ needs.test_and_package_development.outputs.abq_version }}

  release_unstable:
    name: Release new abq to API
    needs: bigtest
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build_and_upload.yml
    with:
      ref: ${{ github.ref }}
      release_channel: unstable
    secrets: inherit
