name: register ABQ version with staging API

on:
  # for automatic release from main on the unstable release channel
  workflow_call:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
      release_channel:
        description: 'release channel'
        required: false
        default: ''
        type: string
    secrets:
      RWX_STAGING_CREATE_RELEASE_ACCESS_TOKEN:
        required: true

jobs:
  release:
    name: Release ABQ
    runs-on: ubuntu-latest
    steps:
      - name: Register a new release with the abq api to a release channel
        if: inputs.release_channel != ''
        run: |
          curl -X "POST" "https://staging.cloud.rwx.com/abq/api/releases" \
          --fail-with-body \
          -H 'Authorization: Bearer ${{ secrets.RWX_STAGING_CREATE_RELEASE_ACCESS_TOKEN }}' \
          -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' \
          --data-urlencode "version=${{inputs.version}}" \
          --data-urlencode "release_channel=${{inputs.release_channel}}"
      - name: Register a new release with the abq api without a release channel
        if: inputs.release_channel == ''
        run: |
          curl -X "POST" "https://staging.cloud.rwx.com/abq/api/releases" \
          --fail-with-body \
          -H 'Authorization: Bearer ${{ secrets.RWX_STAGING_CREATE_RELEASE_ACCESS_TOKEN }}' \
          -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' \
          --data-urlencode "version=${{inputs.version}}"
