name: register ABQ version with staging API

on:
  # for manual release
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
      release_channel:
        description: 'release channel'
        required: true
        type: choice
        options:
          - "v1"
          - "unstable"

  # for automatic release from main on the unstable release channel
  workflow_call:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
      release_channel:
        description: 'release channel'
        required: true
        type: string
    secrets:
      RWX_PRODUCTION_CREATE_RELEASE_ACCESS_TOKEN:
        required: true

jobs:
  release:
    name: Release ABQ
    runs-on: ubuntu-latest
    steps:
      - name: Register new release abq api
        run: |
          curl -X "POST" "https://abq.build/api/releases" \
          -H 'Authorization: Bearer ${{ secrets.RWX_PRODUCTION_CREATE_RELEASE_ACCESS_TOKEN }}' \
          -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' \
          --data-urlencode "version=${{inputs.version}}" \
          --data-urlencode "release_channel=${{inputs.release_channel}}"
